FROM node:alpine AS build
WORKDIR /app
COPY package*.json .
RUN npm install
COPY . .

FROM node:alpine as runtime
WORKDIR /app
COPY --from=build /app/* /app/
CMD ["npm","run","dev"]

FROM node:alpine

WORKDIR /app

COPY . .

RUN npm install

CMD ["npm","run","dev"]